[book]
authors = ["TeleporterX"]
language = "en"
multilingual = false
src = "src"
title = "Mutual Fund Broker Web Application"

[output.html]
default-theme = "Rust"

# Enable collapsible sections in the sidebar
[output.html.fold]
enable = true